import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Zoro UK App',
	description: 'Zoro UK test App, Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		// `data-theme` controls the DaisyUI theme
		<html lang='en' data-theme='light'>
			<body className={inter.className}>{children}</body>
		</html>
	);
}
